#!/usr/bin/env python

#
# Track portfolios of market participants.
#
# This script reads the output of Parity Trade Reporter as tab-separated
# values (TSV) from the standard input and writes output to the standard
# output as TSV.
#

import collections
import csv
import sys

class User(object):

    def __init__(self):
        self.cash = 0
        self.inventory = {}

users = collections.defaultdict(User)

print '\t'.join(['Timestamp', 'Username', 'Cash', 'Inventory'])

def record(timestamp, username):
    user = users[username]
    cash = '{:.2f}'.format(user.cash)
    inventory = ','.join(sorted('{}:{}'.format(instrument, quantity) for
        instrument, quantity in user.inventory.iteritems()))
    print '\t'.join([timestamp, username, cash, inventory])

for row in csv.DictReader(sys.stdin, delimiter='\t'):
    timestamp  = row['Timestamp']
    instrument = row['Instrument']
    price    = float(row['Price'])
    quantity = int(row['Quantity'])
    seller = users[row['Seller']]
    buyer  = users[row['Buyer']]
    seller.cash += price * quantity
    buyer.cash  -= price * quantity
    seller.inventory[instrument] = seller.inventory.get(instrument, 0) - quantity
    buyer.inventory[instrument]  = buyer.inventory.get(instrument, 0)  + quantity
    record(timestamp, row['Seller'])
    record(timestamp, row['Buyer'])
